CREATE TABLE IF NOT EXISTS "question" (
	"id" INTEGER NOT NULL UNIQUE,
	"text" VARCHAR NOT NULL UNIQUE,
	"entities" TEXT,
	"answer_id" INTEGER NOT NULL UNIQUE,
	"note_id" INTEGER UNIQUE,
	PRIMARY KEY("id"),
	FOREIGN KEY ("answer_id") REFERENCES "answer"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("note_id") REFERENCES "note"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "answer" (
	"id" INTEGER NOT NULL UNIQUE,
	"text" VARCHAR NOT NULL,
	"entities" TEXT,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "note" (
	"id" INTEGER NOT NULL UNIQUE,
	"text" TEXT,
	PRIMARY KEY("id")
);
